#!/bin/sh

die () {
    echo >&2 "$@"
    exit 1
}

ROOT=${0%/*}
ROOT=`cd "${ROOT}" && pwd -P`

[ $# -ge 1 ] || die "Please specify a grammar file to be compiled or an egt file to be recompiled"

exec make -f "$ROOT/Makefile" ROOT="$ROOT" $*
