include ../Make.options
include ../Project.options

.PHONY: default
default:
	cd GOLD-Builder-Cmd && $(MAKE) default
	cd ANSI-C-Engine && $(MAKE) default

.PHONY: clean
clean:
	cd GOLD-Builder-Cmd && $(MAKE) clean
	cd ANSI-C-Engine && $(MAKE) clean
